name: catbreeds
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.2
  flutter_riverpod: ^2.6.1
  go_router: ^14.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon.png"
  ios: true
  image_path: "assets/icon/iconcat.png"
  android_adaptive_icon_background: "assets/icon/background.png"
  android_adaptive_icon_foreground: "assets/icon/foreground.png"
  min_sdk_android: 21

flutter_native_splash:
  background_image: assets/icon/splash.png  
  android: true  
  ios: true  
  web: true   
  ios_content_mode: "scaleAspectFit"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icon/
